[font]
normal = { family = "Caskaydia Cove Nerd Font", style = "Regular" }
bold   = { family = "Caskaydia Cove Nerd Font", style = "Bold"    }
italic = { family = "Caskaydia Cove Nerd Font", style = "Italic"  }
size   = 12

[window]
dimensions = { columns = 120, lines = 32  }

[colors.primary]
foreground = "#fefefe"
background = "#0f1014"

[colors.normal]
black   = "#0f1014"
red     = "#cb333a"
green   = "#188743"
yellow  = "#faa821"
blue    = "#3870ed"
magenta = "#f5c2e7"
cyan    = "#007f7f"
white   = "#fefefe"

[colors.bright]
black   = "#2c2e30"
red     = "#cb333a"
green   = "#188743"
yellow  = "#faa821"
blue    = "#3870ed"
magenta = "#dc25b6"
cyan    = "#007f7f"
white   = "#c4c7c5"
